/**
 * Copyright 2010 The University of Nottingham
 * 
 * This file is part of mixedrealitycreator.
 *
 *  mixedrealitycreator is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  mixedrealitycreator is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with mixedrealitycreator.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */
package uk.ac.horizon.ug.mrcreator.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import com.google.appengine.api.datastore.Key;
import com.google.appengine.api.datastore.KeyFactory;

/** an Item's membership of a Collection (or Space).
 * 
 * @author cmg
 *
 */
@Entity
public class Membership {
	/** key - autogenerated */
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY) 
    private Key key; 
    
    /** item key */
    private Key itemKey;
    /** collection key */
    private Key contextKey;
    /** creator (ID) */
    private String creator;
    /** created date/time (Java time) */
    private long created;
    /** sort value (for ordered collection) */
    private String sortValue;
    /** (other) json-encoded metadata */
    private String metadata;
    
    /** cons */
    public Membership() {
    	
    }
    /** generate key */
    public static final Key idToKey(String id) {
    	return KeyFactory.createKey(Membership.class.getSimpleName(), id);
    }

	/**
	 * @return the key
	 */
	public Key getKey() {
		return key;
	}

	/**
	 * @param key the key to set
	 */
	public void setKey(Key key) {
		this.key = key;
	}
	/**
	 * @return the id (string of key)
	 */
	public String getId() {
		if (key!=null)
			return key.getName();
		else
			return null;
		//return id;
	}
	/**
	 * @return the itemKey
	 */
	public Key getItemKey() {
		return itemKey;
	}
	/**
	 * @param itemKey the itemKey to set
	 */
	public void setItemKey(Key itemKey) {
		this.itemKey = itemKey;
	}
	/**
	 * @return the contextKey
	 */
	public Key getContextKey() {
		return contextKey;
	}
	/**
	 * @param contextKey the contextKey to set
	 */
	public void setContextKey(Key contextKey) {
		this.contextKey = contextKey;
	}
	/**
	 * @return the creator
	 */
	public String getCreator() {
		return creator;
	}
	/**
	 * @param creator the creator to set
	 */
	public void setCreator(String creator) {
		this.creator = creator;
	}
	/**
	 * @return the created
	 */
	public long getCreated() {
		return created;
	}
	/**
	 * @param created the created to set
	 */
	public void setCreated(long created) {
		this.created = created;
	}
	/**
	 * @return the sortValue
	 */
	public String getSortValue() {
		return sortValue;
	}
	/**
	 * @param sortValue the sortValue to set
	 */
	public void setSortValue(String sortValue) {
		this.sortValue = sortValue;
	}
	/**
	 * @return the metadata
	 */
	public String getMetadata() {
		return metadata;
	}
	/**
	 * @param metadata the metadata to set
	 */
	public void setMetadata(String metadata) {
		this.metadata = metadata;
	}
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Membership [contextKey=" + contextKey + ", created=" + created
				+ ", creator=" + creator + ", itemKey=" + itemKey + ", key="
				+ key + ", metadata=" + metadata + ", sortValue=" + sortValue
				+ "]";
	}
}
